apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
     - name: nginx
       image: carlosgutierrez90/custom-nginx:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 8081