# Usar la imagen base de Nginx
FROM nginx:alpine

# Copiar los archivos HTML, CSS y JS en el directorio por defecto de Nginx
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY script.js /usr/share/nginx/html/script.js